// This file is released under the 3-clause BSD license. See COPYING-BSD.
// Generated by builder.sce : Please, do not edit this file
// cleaner.sce
// ------------------------------------------------------
curdir = pwd();
cleaner_path = get_file_path('cleaner.sce');
chdir(cleaner_path);
// ------------------------------------------------------
if fileinfo('loader.sce') <> [] then
  mdelete('loader.sce');
end
// ------------------------------------------------------
if fileinfo('libpointcloud_toolbox.so') <> [] then
  mdelete('libpointcloud_toolbox.so');
end
// ------------------------------------------------------
if fileinfo('libpointcloud_toolbox.cpp') <> [] then
  mdelete('libpointcloud_toolbox.cpp');
end
// ------------------------------------------------------
if fileinfo('libpointcloud_toolbox.hxx') <> [] then
  mdelete('libpointcloud_toolbox.hxx');
end
// ------------------------------------------------------
if fileinfo('libpointcloud_toolbox.h') <> [] then
  mdelete('libpointcloud_toolbox.h');
end
// ------------------------------------------------------
chdir(curdir);
// ------------------------------------------------------
